version: '3'

services:
  mongo:
    image: mongo
    env_file:
      - .env
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/"
    depends_on:
      - mongo
    networks:
      - app

  nats:
    image: nats:2.3.4-alpine
    env_file:
      - .env
    ports:
      - "4222:4222"
      - "8222:8222"
    container_name: nats
    restart: always
    networks:
      - app

  nats-web:
    image: sphqxe/nats-webui
    ports:
      - "80:80"
    container_name: nats-web
    restart: always
    networks:
      - app

networks:
  app:
    external: true